# version: "3.9"

services:
  web:
    build: .
    command: ["/start.sh"] #  IN START.SH FILE " gunicorn lms_project.wsgi:application --bind 0.0.0.0:8000 ""
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0 
    

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 834000
    ports:
      - "5432:5432"
    
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A lms_project worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0 

  celery-beat:
    build: .
    command: celery -A lms_project beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis

volumes:
  pgdata:
  static_volume:
  media_volume:

# environment:
#   - DJANGO_SETTINGS_MODULE=lms_project.settings

